# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDBApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDBApp
    pod 'SnapKit', '~> 5.6.0'
    pod 'Alamofire'
    pod 'Kingfisher', '~> 7.0'

end
